# Generated by Django 3.2.9 on 2021-11-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
    ]
