# Generated by Django 3.2.9 on 2021-12-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time_slot',
        ),
    ]
