# Generated by Django 3.2.9 on 2021-12-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time_slot',
        ),
    ]
