# Generated by Django 3.2.9 on 2021-12-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_slot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
