# Generated by Django 3.2.9 on 2021-12-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20211130_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_total',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
