# Generated by Django 3.2.9 on 2021-12-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20211210_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_slot',
        ),
    ]
