# Generated by Django 3.2.9 on 2021-12-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_auto_20211212_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
