# Generated by Django 3.2.9 on 2021-12-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_auto_20211212_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
    ]
