# Generated by Django 3.2.9 on 2021-12-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_auto_20211213_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_picked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
