# Generated by Django 3.2.9 on 2021-12-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_orderitem_date_picked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_slot',
        ),
    ]
